# Medical Rep API - Production Environment Configuration

app:
  environment: "production"
  debug: false

http:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  tls:
    enabled: true
    cert_file: "/etc/ssl/certs/app.crt"
    key_file: "/etc/ssl/private/app.key"
  cors:
    allowed_origins:
      - "https://yourdomain.com"
      - "https://api.yourdomain.com"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
      - "PATCH"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
      - "X-API-Key"
  rate_limit:
    enabled: true
    rate: 1000.0
    burst: 2000

database:
  host: "prod-db-host"
  port: 5432
  database: "medical_rep_prod"
  username: "app_user"
  ssl_mode: "require"
  max_open_conns: 100
  max_idle_conns: 20
  conn_max_lifetime: "10m"

redis:
  host: "prod-redis-host"
  port: 6379
  database: 0
  pool_size: 50
  dial_timeout: "10s"
  read_timeout: "5s"
  write_timeout: "5s"

auth:
  jwt_expiration: "8h"
  bcrypt_cost: 14

logging:
  level: "warn"
  format: "json"
  output: "/var/log/medical-rep/app.log"
  max_size: 500
  max_backups: 10
  max_age: 90
  compress: true

health:
  enabled: true
  check_interval: "60s"
  timeout: "10s"
  database_check: true
  redis_check: true
  external_checks:
    - "https://external-api.com/health"